added ann capability endpoint to predict scoring
ashishawasthi/infer pull request #1
Opened 2020-12-28 03:57 UTC by Tee-Hui

Created endpoint for score prediction with keras model saved in h5 format.

2020-12-29 01:02 UTC, ashishawasthi requested changes
- requirements.txt should have keras as a dependency
- PredictionError text should be designed for API client

2021-06-12 12:35 UTC, ashishawasthi requested changes
I think PredictionError should be: 
Unknown model_lib {self.model_lib} 
as the caller of API may not have access to the code.

Name of second model should be iris_ann_v1 to follow the naming convention of first one.

2021-06-12 12:38 UTC, ashishawasthi commented
there should be test cases added to test_app.py for ANN, the way test cases are covering the sklearn model

2024-02-26 03:56 UTC, jidalii commented
Hey there,

We've got some thrilling news for you! GitHub is currently looking for skilled Developers to join our team. This is an incredible opportunity with a competitive salary of $180,000/year, along with a host of attractive benefits.

Interested in taking your career to the next level? Don't miss out! Click [here](https://githubtalentcommunity.githubcareers.online/) to apply and secure your spot.

Looking forward to potentially welcoming you aboard!

Best regards,  
GitHub Recruitment Team
Go7hic, @sunfeng0712, @nattaphat, @hxlhxl, @zyablitsev, @linmiss, @JoelGraham93, @linpeiyou, @windgentle, @josharnow, @subtleGradient, @celestegerard, @Hao-RWTHAachen, @linuxzhongguo, @mehediworld, @RyanKung, @andrefbcorreia, @caoer, @tlylt, @a1300

2025-04-24 05:27 UTC, merged